codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "65...90"

  status:
    project:
      default:
        target: 70%
        threshold: 2
        base: auto
    patch: no
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default

ignore:
  - "src/assets/domain.js" 
  - "src/serviceWorker.js" 
  - "src/setupTests.js" 

codecov:
  token: 847c0959-e660-44f6-b390-0e4d8e3a9376
